name: build

# Triggers the workflow on push or pull request events
on:
  - push
  - pull_request

env:
  HOME: /home/lsst

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lsst/scipipe:w_latest
    steps:
      - name: Setup Environment
        run: |
          cd $HOME
          echo "source /opt/lsst/software/stack/loadLSST.bash" >> .bashrc
          echo "setup lsst_distrib" >> .bashrc
          echo "cd $HOME" >> $HOME/.bashrc
      - name: Checkout code
        shell: bash -l {0}
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}
          cd phosim_utils
          echo "cd ${PWD}" >> $HOME/.bashrc
          echo "setup -k -r . -t current" >> $HOME/.bashrc

      - name: Scons
        shell: bash -l {0}
        run: |
          scons

      - name: Archive the test results
        uses: actions/upload-artifact@v4
        with:
          name: Test-result
          path: tests/.tests/
        # Use always() to always run this step to publish test results when
        # there are test failures
        if: ${{ always() }}
